### ISSUE TITLE
Add type validation to toRoman function.

### ISSUE THREAD

**Issue by Zubs** [Zubs/toRoman#7]
Currently, the function only checks iframe the value is not null and within a range of 0 and 4000. It doesn't check input to be sure it's an actual digit.

**Comment by KelseyJr** [comment]
Hi @Zubs , can I work on it?

**Comment by Zubs** [comment]
Feel free to make a PR.

You’re welcome.

**Comment by Harithmetic1** [comment]
Hi, @Zubs would love to contribute to this. Can I make a PR?
